# Generated by Django 3.2.7 on 2021-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('desserte', models.CharField(max_length=200, verbose_name='desserte')),
                ('pmr', models.BooleanField(verbose_name='pmr')),
                ('ascenseur', models.BooleanField(verbose_name='ascenseur')),
                ('escalator', models.BooleanField(verbose_name='escalator')),
                ('gid', models.IntegerField(verbose_name='gid')),
                ('last_update', models.DateTimeField(max_length=200, verbose_name='last_update')),
                ('last_update_fme', models.DateTimeField(max_length=200, verbose_name='last_update_fme')),
                ('coord1', models.DecimalField(decimal_places=20, max_digits=45)),
                ('coord2', models.DecimalField(decimal_places=20, max_digits=45)),
            ],
        ),
    ]
