# Generated by Django 3.2.7 on 2021-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='values__id')),
                ('nom', models.CharField(max_length=20, verbose_name='values__nom')),
                ('desserte', models.CharField(max_length=20, verbose_name='values__desserte')),
                ('pmr', models.BooleanField(verbose_name='values__pmr')),
                ('ascenseur', models.BooleanField(verbose_name='values__ascenseur')),
                ('escalator', models.BooleanField(verbose_name='values__escalator')),
                ('gid', models.IntegerField(verbose_name='values__gid')),
                ('last_update', models.CharField(max_length=20, verbose_name='values__last_update')),
                ('last_update_fme', models.CharField(max_length=20, verbose_name='values__last_update_fme')),
            ],
        ),
    ]
