# Generated by Django 3.2.7 on 2021-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='ascenseur',
            field=models.BooleanField(verbose_name='ascenseur'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='desserte',
            field=models.CharField(max_length=20, verbose_name='desserte'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='escalator',
            field=models.BooleanField(verbose_name='escalator'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='gid',
            field=models.IntegerField(verbose_name='gid'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='last_update',
            field=models.CharField(max_length=20, verbose_name='last_update'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='last_update_fme',
            field=models.CharField(max_length=20, verbose_name='last_update_fme'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='nom',
            field=models.CharField(max_length=20, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='pmr',
            field=models.BooleanField(verbose_name='pmr'),
        ),
    ]
