# Generated by Django 3.2.7 on 2021-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210919_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='desserte',
            field=models.CharField(max_length=200, verbose_name='desserte'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='last_update',
            field=models.CharField(max_length=200, verbose_name='last_update'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='last_update_fme',
            field=models.CharField(max_length=200, verbose_name='last_update_fme'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
    ]
