# Generated by Django 3.2.7 on 2021-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210921_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='ascenseur',
            field=models.BooleanField(default=False, verbose_name='ascenseur'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='escalator',
            field=models.BooleanField(default=False, verbose_name='escalator'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='gid',
            field=models.IntegerField(default=False, verbose_name='gid'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='pmr',
            field=models.BooleanField(default=False, verbose_name='pmr'),
        ),
    ]
