# Generated by Django 3.2.7 on 2021-09-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210919_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='last_update',
            field=models.DateTimeField(max_length=200, verbose_name='last_update'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='last_update_fme',
            field=models.DateTimeField(max_length=200, verbose_name='last_update_fme'),
        ),
    ]
